ci:
  - changed-files:
    - any-glob-to-all-files:
      - .github/**

documentation:
  - changed-files:
    - any-glob-to-all-files:
      - CONTRIBUTING.md
      - CHANGELOG.md
      - README.md

test:
  - changed-files:
      - any-glob-to-all-files:
          - test/**
          - integration_test/**
          - macos/RunnerTests/**
          - macos/RunnerUITests/**

dart:
  - changed-files:
      - any-glob-to-all-files:
          - lib/**/*.dart
          - test/**/*.dart

swift:
  - changed-files:
      - any-glob-to-all-files:
          - macos/**/*.swift

linux:
  - changed-files:
      - any-glob-to-all-files:
          - linux/**

macos:
  - changed-files:
      - any-glob-to-all-files:
          - macos/**

windows:
  - changed-files:
      - any-glob-to-all-files:
          - windows/**

assets:
  - changed-files:
      - any-glob-to-all-files:
          - assets/**

localizations:
  - changed-files:
      - any-glob-to-all-files:
          - l10n/**

scripts:
  - changed-files:
      - any-glob-to-all-files:
          - scripts/**
